### ISSUE TITLE
Typo in Udana Intro

### ISSUE THREAD

**Issue by reverendj1** [suttacentral/editions#4]
Hello,
Thank you for making these available! I was reading the Udana and noticed a typo in the introduction, the `The place of the Udāna and its relation to the Dhammapada` section:

Traditionally it would act as a mnemonic, so that reciters could check that ~~that~~ **they** had remembered all the suttas of that chapter.

**Comment by sujato** [comment]
Thanks, this is already fixed. 

We have a dedicated thread for mistakes, which is likely to catch my eye sooner than here:

https://discourse.suttacentral.net/t/bring-the-happiness-that-most-people-only-dream-about-tell-us-our-mistakes/26960/192
