### ISSUE TITLE
editions-2023-04-24 have reverse table of contents

### ISSUE THREAD

**Issue by vijjo** [suttacentral/editions#5]
All suttas are in reverse order. For example, the Long Discourse:

<img width="236" alt="image" src="https://user-images.githubusercontent.com/31264468/235037619-8db3db91-ba6d-45a9-a466-1b5e04689705.png">

The Linked Discourse:

<img width="927" alt="image" src="https://user-images.githubusercontent.com/31264468/235038049-e0e49b15-8885-40d9-849a-8c47ad6f14d7.png">

**Comment by sujato** [comment]
Again, this seems to have been resolved. Thanks for your feedback and do let us know if it recurs.
