### ISSUE TITLE
ePub chapter contents empty - all the text after the last 'chapter'

### ISSUE THREAD

**Issue by upekshapriya** [suttacentral/editions#6]
In the Digha Nikaya for example the Chapters 'The Chapter on the Entire Spectrum of Ethics', 'The Great Chapter' and 'The Chapter with Pāṭikaputta' all appear in the file in order with no content within them, with the suttas that should be in there all shown after 'The Chapter with Pāṭikaputta' - unlike https://suttacentral.net/pitaka/sutta/long/dn

This is the case in other places, especially in the Saṁyutta Nikāya where there are dozens of chapters with no content and the suttas all listed after the last chapter!

**Comment by sujato** [comment]
It looks like this bug has been resolved, sorry for the hassle. In the lastest version I am testing now, it seems correct. I'll close this issue, but please open a new one if this recurs.
