### ISSUE TITLE
missing endnotes.xhtml files in some epubs

### ISSUE THREAD

**Issue by BBBalls** [suttacentral/editions#8]
The editions epubs for the books below are missing the endnotes.xhtml files, breaking the internal linking. All epubs downloaded 20-10-23.

mn
thag
thig
iti
dhp

**Comment by sujato** [comment]
Thanks, this appears to overlap with #19, I'll add it there.

**Comment by agilgur5** [comment]
> Thanks, this appears to overlap with #19, I'll add it there.

Probably meant #10 😅
For reference, see https://github.com/suttacentral/editions/issues/10#issuecomment-2295045350
