### ISSUE TITLE
Arno pro font used in the project appears to need licensing from Adobe.

### ISSUE THREAD

**Issue by pingssgp** [suttacentral/editions#9]
The Arno Pro font used in the project appears to require licensing from Adobe before I can use it. Looking through the .tex files, I see that at least the Arno pro regular, caption, semibold fonts are used.

Perhaps the team already has the licenses, but as a non-subscriber to Adobe CC I can't use these fonts.

Adobe font licensing FAQ: https://helpx.adobe.com/fonts/using/font-licensing.html

Adobe fonts service additional T&C (PDF warning): https://wwwimages2.adobe.com/content/dam/cc/en/legal/servicetou/Adobe_Fonts_Additional_Terms_en_US_20220715.pdf

**Comment by pingssgp** [comment]
Was there any update on this issue?

**Comment by sujato** [comment]
You are correct, the font does need to be licensed, and SC has purchased the license. It's only valid for SC use, so if you want to create your own editions you'll have to supply your own fonts.

Note, however, that we use a bespoke version of the font that we had customized for this project to include the relevant Sanskrit diacriticals. So you can't use regular Arno.

**Comment by agilgur5** [comment]
Thought I'd add a small follow-up note from a [related forum thread](https://discourse.suttacentral.net/t/help-building-latex-editions-of-translations/37216/4?u=agilgur5) here: you can use [Gentium Plus](https://fonts.google.com/specimen/Gentium+Plus) as a FOSS alternative for Arno. Or similar [Gentium fonts](https://github.com/silnrsi/font-gentium)
I don't know how much it may affect the layout or anything, just thought I'd note that as an option for folks who see this issue as I did!
